### ISSUE TITLE
Changing Colors of input and ouput 

### ISSUE THREAD

**Issue by prabh1601** [Jatana/FastOlympicCoding#15]
Well one thing to note is that the colors of integer output are different from character output data.. 
This ain't much of a problem but it does affect the perceiving the output data and such.. 
So I was just wondering that is it possible to have single color for the same and also is it possible to customize the colors as per the desired..
Thanks in advanced for the same!

**Comment by Jatana** [comment]
Sublime Text uses [syntax defining files](https://www.sublimetext.com/docs/3/syntax.html) to highlight text.

To change the default syntax highlighting, you can modify [Packages/CppFastOlympicCoding/TestSyntax.sublime-syntax](https://github.com/Jatana/FastOlympicCoding/blob/master/TestSyntax.sublime-syntax) file.

**Comment by prabh1601** [comment]
Well thanks for the help, I am going through the documentations you provided but still I ain't sure or maybe getting the point that what things I need to modify in the syntax file. I code for the same would be very nice of you, although even if you can guide me that what i need to do instead, that would more than enough nice gesture.

**Comment by Jatana** [comment]
Try the following:
```
%YAML 1.2
---
name: TestSyntax
file_extensions: []
scope: source.TestSyntax

contexts:
  main:
    - match: Test
      scope: storage.type.OPD
    - match: "(} )(out)( {)"
      captures: 
        2: storage.type.OPD
    - match: (} )(rtcode)
      captures:
        2: storage.type.OPD
```
